Lksm
nutsfinance/merkle-distributor pull request #2
Opened 2022-08-11 16:38 UTC by qwer951123

2022-08-14 16:20 UTC, qwer951123 commented
@shengda

2022-08-15 01:51 UTC, shengda requested changes

2022-08-15 01:51 UTC, shengda commented on rewards/run_lksm.ts
> +const main = async () => {
Do you want to run LKSM and taiKSM as separate pipeline or a single one?

2022-08-15 01:51 UTC, shengda commented on rewards/run_taiksm.ts
> +    await distributeLKSM(block);
If you want to run lksm distribution as a separate pipeline, then this task is not part of the taiKSM pipeline.

2022-08-15 01:51 UTC, shengda commented on rewards/distribute-lksm.ts
> +                distributionContent += `reserved-${address},${reserved[address].toString()}\n`;
The format is: [user address], reserve-[token address]

2022-08-15 02:38 UTC, merged